
site_name: í¸ ê°€ì´ë“œ
theme:
  name: material
  logo: images/pyeon_logo.jpg
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: blue
  font:
    text: Noto Sans KR
    code: Fira Code
extra_css: 
    - stylesheets/extra.css

nav: 
  - í™ˆ: index.md
  - ğŸ’­íŒ€ ì†Œê°œ:
     - íŒ€ ì—­ì‚¬: team_introduction/team_introduction.md
     - íŒ€ ì„¤ëª…: team_introduction/team_explanation.md
     - íŒ€ ë¯¸ë˜: team_introduction/team_future.md
  - í¸ ì•¼êµ¬ë‹¨ ì°¸ì—¬ë¦¬ê·¸ì™€ ì •ê¸°í›ˆë ¨: leagues/pyeon_league_and_activity.md
  - í¸ ì•¼êµ¬ë‹¨ íšŒë¹„, ë¦¬ê·¸ë¹„: money/team_needs_money.md
  - í¸ ì•¼êµ¬ë‹¨ ìš´ì˜ìœ„ì›íšŒ ì†Œê°œ: team_introducing/team_introducing_executives.md
  - í¸ ì•¼êµ¬ë‹¨ íŒ€ì› ì†Œê°œ: team_introducing/team_introducing_members.md
  - í¸ ì•¼êµ¬ë‹¨ ê°œì¸ìƒí•´ë³´í—˜, ì•ˆì „: insurance/team_insurance.md
  - ì‚¬íšŒì¸ì•¼êµ¬ ê¸°ë³¸ ì˜ˆì ˆ: baseballrules/manual_manners.md
  - âœ…í¸ ì•¼êµ¬ë‹¨ ê·œì •:
     - ë²Œê¸ˆ ê·œì •: money/killyou.md
     - ê²½ê¸°ì‹œ ê¶Œì¥ ë‚´ìš©: money/good.md
  - ìœ ë‹ˆí¼, íŒ€ì˜ë¥˜ ì£¼ë¬¸ ë°©ë²•: uniforms/how_to_order.md
  - âš¾ì•¼êµ¬ í¬ì§€ì…˜ ì„¤ëª…: 
     - ê¸°ë³¸ ì„¤ëª…: about_position/basic_position.md
     - ìƒì„¸ ì„¤ëª…: about_position/position.md
  - í¸ ì•¼êµ¬ë‹¨ ê°€ì…ì‹ ì²­ì„œ: join/how_to_get_in_pyeon.md
  - í¸ ì•¼êµ¬ë‹¨ ê²Œì„ì›: gameone/gameonesite.md